name: Build iOS App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Select Xcode 16 (for iOS 18)
        run: sudo xcode-select -s /Applications/Xcode_16.0.app

      - name: Build the app
        run: |
          set -o pipefail
          xcodebuild clean build \
            -project Geezmo.xcodeproj \
            -scheme Geezmo \
            -sdk iphoneos \
            -configuration Release \
            -destination 'generic/platform=iOS' \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            | tee build.log | xcpretty

      - name: Upload xcodebuild log if build fails
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: build.log
