name: iOS 18 App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-14  # or macos-latest, macos-13, etc.

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Select Xcode version (Xcode 16 for iOS 18)
        run: sudo xcode-select -s /Applications/Xcode_16.0.app

      - name: Install CocoaPods (if needed)
        run: pod install
        working-directory: ./YourProjectFolder

      - name: Build the app
        run: |
          xcodebuild clean build \
            -workspace YourApp.xcworkspace \
            -scheme YourAppScheme \
            -sdk iphoneos \
            -configuration Release \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
